applied to specification

diff --git a/latc_x86 b/latc_x86
--- a/latc_x86
+++ b/latc_x86
@@ -2,7 +2,7 @@
 
 if [ ! -f ./dist/build/compile/compile ]
 then
-    echo "Could not find the proper executable. Did you run \"make\"?"
+    >&2 echo "Could not find the proper executable. Did you run \"make\"?"
     exit 1
 fi
 
@@ -10,7 +10,15 @@ FULL_PATH=$1
 
 if [ -z ${FULL_PATH} ]
 then
+    >&2 echo "ERROR"
     echo "Usage: $0 INPUT_FILE"
+    exit 1
+fi
+
+if [ ! -f ${FULL_PATH} ]
+then
+    >&2 echo "ERROR"
+    echo "No such file: ${FULL_PATH}"
     exit 1
 fi
 
